name: CI

on:
  push:
    branches:
      - "**"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Move to frontend directory
      run: cd front-end
      
    - name: Install dependencies
      run:  npm install
