name: CI

on:
  push:
    branches:
      - "**"  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run:  cd front-end/ && npm install
