name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ID: ${{ secrets.VERCEL_ID }}
on:
  pull_request: 
    branches:
      - preview

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ID }}
      - name: Install dependencies
        run: cd front-end && npm i
      - name: Build app
        run: cd front-end && npm run build
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_ID }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_ID }}